---
#title: "CHON: From physical metaphor to musical gesture"
#author: Rodney DuPlessis
#date: April 2021
toc: true
numbersections: true
csl: ieee.csl
bibliography: references.bib
link-citations: true
documentclass: report
geometry:
- left=1.25in
- right=1in
- top=1in
- bottom=1in
fontsize: 12pt
linestretch: 1.25
---
