# Physical metaphor in music

The primary goal of CHON is to generate musical gestures based on the dynamics of a particular physical system -- a coupled oscillator network. This is part of my broader investigation into physical metaphors in music. In this section I will discuss why and how I use physics to shape my music. I will then explain how this motivated the creation of CHON.

I am interested in physics and physical metaphor in composition because it can provide a visceral and universal logical framework for music. I will parse this statement in reverse order starting with the idea of a logical framework.

## Logical Framework

I use the term logical framework to describe a set of rules that more or less constrain the possible states and transformations of a system. A logical framework is also a mental anchor that allows one to make inferences and predictions about the behavior of the system. The system in question is music and the logical framework constrains the structure and progression of music. This is closely related to what Fred Lerdahl calls *musical grammar* [@lerdahl_cognitive_1992] and is comprised of a network of overlapping *causal logic* [@bodin_music_2004].

Composers apply logical frameworks to shape music at every level, to cull the infinite possibilities of arranging sound in time. Listeners employ logical frameworks as they discover and parse patterns and relations in music. The degree to which the frameworks of both parties align can vary greatly. These frameworks can also be active or passive, conscious or unconscious.

A logical framework suggests a set of causes and effects, which create expectations. A dominant chord in tonal music creates tension which seems to cause the release of tension via a tonic chord just like knocking a ball off of a table causes it to fall. A build-up in Electronic Dance Music seems to inevitably lead to a bass-drop the way over-inflating a balloon causes it to pop. These causal networks are illusory, but nonetheless crucial to musical reasoning. As Curtis Roads [@roads_composing_2015, 328] points out:

> An impression of causality implies predictability. If listeners are not able to correlate sonic events with any logic, the piece is an inscrutable cipher.

Music must rely on a logical framework to form a coherent narrative and carry meaning. The "meaning" I am referring to here is not necessarily tied to programmatic or referential elements. Narrative meaning can arise from the relationship between elements, regardless of the identities of the elements themselves. Byron Almén [@almen_theory_2008, 13] suggests that the abstract nature of musical narrative is one of its strengths (relative to literary or dramatic narrative, for example), allowing it to express a narrative without being bound to specific characters and settings.

A logical framework can emerge from preexisting stylistic conventions, extra-musical referential inheritance, and algorithmic design, among other things. A framework is often formed from a mixture of sources. This creates a tangled web of rules and relationships that allows room for multiple potentialities as they come into conflict. Conflicting rules create crisis, which opens up multiple possibilities for resolution. This in turn drives the narrative forward. This is an important ingredient for creating a compelling narrative as Almén [@almen_theory_2008, 52] notes:

> The psychologically compelling nature of the narrative arises from this perspective of progressive temporality: one cannot know the outcome of a narrative conflict in advance. There is always more than one possible resolution of a crisis, and to reduce out this uncertainty is to remove the essence of narrative.
 
Some logical frameworks are hopelessly complex and esoteric, such that the listener will almost certainly not be able to follow the logic of the piece's structure. On the other hand, a logical framework can be so simple that there is no uncertainty as to where the piece will go next. Complete chaos and complete predictability will bore the listener. It is up to the composer to craft a work that balances the two.

The composer's logical framework can be influenced by overt compositional strategies as well as more implicit biases. Some of these factors may be more or less unconscious, but the most effective composers are self-aware enough to balance them judiciously to shape their music into a compelling narrative. It is not guaranteed that a listener will hear the narrative or the structures that the composer intends. In fact, when one considers the multitude of possible influences on a listener's experience, from past experience to current mood, it seems highly unlikely. I imagine the relationship of composer's and listener's respective logical frameworks to be asymptotic: they can approach each other, but never completely align. This disconnect between the composer's intention and the listener's experience is part of the magic of music. Nevertheless, the power of shared experience is strong, and composers can utilize that to present persuasive musical proposals to the listener. 


## Universal

In some music, there is a logical framework which has been agreed upon (explicitly or implicitly) by composers and listeners. This is a cultural logic, it is not universal or innate to human experience. At one time, the cultural framework of tonal music provided a rapport between Western composers and listeners, which in turn allowed composers to play with expectations to convey musical narratives. Because it had been decided that a dominant chord should resolve to the tonic, it meant something when the dominant chord led to something else. It has been some time now since composers in the Western tradition began to radically break from this cultural agreement and explore other logical frameworks.

Musique concrète, initiated by Pierre Schaeffer in the late 1940s, was perhaps the furthest removed from traditional Western Classical music. Whereas some new directions changed the rules of dealing with musical material (melody, harmony, rhythm), musique concrète expanded the very category of what could be considered musical material. Western Classical music had no framework at all for dealing with recorded sounds such as paper ripping or doors creaking. This medium provided a great deal of freedom for the composer to explore the possibilities of sound organization. There were no rules of pitch or harmony, no rhythmic pulse in most cases, no restriction on the palette of sounds available to the composer. 

This freedom came at a price: listeners and composers could no longer benefit from the established context of tonal music. The challenge now for composers was to write music that drew from other frameworks or that could establish its own context. In the case of musique concrète, the very sounds used were often recognizable and so the context was provided by everyday soundscapes. Acousmatic music plays with that very recognizability to create meaning. This is only one example. Hundreds of genres, styles, and practices emerged in the 20th century, each with their own logic.

In my own early work, I found myself inventing a new logic for almost every piece. Some were mathematical, others more vague. With these works, I needed to establish the grammar of the piece within the piece itself, or else rely on extensive program notes to explain the context of the piece (a sure way to alienate listeners). Establishing the logic of a piece within itself typically involves a great deal of repetition and consistency. Like Pavlov's bell, if a sound is consistently followed by another sound, they will come to seem related by some causal logic. This way, the process of the piece is made clear.

This approach of establishing new logic for each piece is way to bridge the gap between composer intention and listener experience, but it's an inefficient use of time and listeners only have so much patience. I wanted to find a common ground, something universally understood, to build the frameworks of my future pieces. I found this in physics and physical metaphor. Each piece has its own idiosyncrasies and can add something unique to this basis to build its logical framework, but physics provides the foundation.

Unlike cultural logical frameworks or invented systems, physical metaphor can be understood by anyone because we are all physical beings. We all know intuitively that a ball thrown into the air will fall back down, and that some objects can be moved if we push on them. Our imagination allows us to make inferences based on this knowledge. If we hear a loud crash outside, we understand that some massive objects probably collided. We even do this unconsciously. If I hear a sound getting rapidly louder from behind me, I will move out of the way reflexively because on some level I understand that something is approaching at a high velocity and I can further infer that it will collide with me and cause me harm if I do not move. This is not a cultural or idiosyncratic response. I suspect every person in possession of their faculties would react the same way. 

These are just two examples of how sound can trigger our knowledge of physical interactions and even arouse images and narrative sequences in our imagination. Much more complicated and interesting sonic interactions can be built-up from this basis, but these basic examples illustrate not only the universality of physical logic, but also its unconscious or semi-conscious nature.

## Visceral

All humans understand certain basic physical principles. Some of these physical principles affect our behavior on a fundamental level. We learn about the physical principles of the world as we grow up by observing and by doing. Research into mirror neurons has shown that observation and performance may not be entirely distinct. If seeing or hearing some kinds of events accesses deeper parts of our brains beyond our reasoning centers, then that presents a fertile ground for musical communication.

Mirror neurons are neurons that fire similarly when one performs an action and when observing that same action being performed [@keysers_mirror_2009]. It has been theorized that mirror neurons play a part in empathy, learning new skills, and understanding others' intentions and actions. Much research has been done regarding mirror neurons in humans and primates, mostly focused on visual stimuli [@ferrari_mirror_2014]. However, it has also been shown that the sound of some actions being performed can activate mirror neurons as well [@gazzola_empathy_2006]. Recent research has shown that mirror neurons also fire when listening to music, and that the communication of emotion in music arises at least partially from empathically feeling the motion of the music [@chapin_dynamic_2010]. Music quite literally moves us.

Obviously, many kinds of music using varied logical frameworks can elicit this response. Music has always had the ability to move us. But if we feel music with the same mirror neurons that help us to understand the physical world, then it seems that music based on physical metaphor could access this level of cognition more directly than others. Music can take advantage of the fact that we all understand certain physical principles, and we understand them viscerally.

Of course we do not all understand physics completely or physicists would not need to attend university for years. Science communicators like to surprise audiences with experiments that demonstrate lesser known or poorly understood physical laws. This limit to our understanding provides a fertile ground for creating suspense, surprise, uncertainty, and intrigue in using physical metaphor in music.

## Physical Metaphor in Music

What do I mean by physical metaphor in music, exactly? Metaphorically speaking, one can treat a sound as if it had physical properties such as mass, momentum, inertia, internal energy, heat, entropy, gravity, and others. Physical metaphor involves shaping the evolution of a sound, or a group of sounds, according to how real physical objects with these properties behave. For example, Newton's first law of motion states that an object at rest will remain at rest and an object in motion will remain in motion unless acted upon by an external force. This is the law of inertia. If we follow this law with sounds, then, for example, a sound at rest will remain at rest unless it is excited by some force, which could be another sound entering the field and colliding with it. The momentum of a sound and the metaphorical collision of sounds can take shape entirely in the imagination of the composer, and this is a rich domain for creativity.

Edgard Varèse was one of the first composers to appreciate this potential well of musical expression. He spoke of sound-masses, points of attraction and repulsion, and shifting planes, employing physical language extensively to describe his vision of the future of music [@varese_liberation_1966]. Iannis Xenakis took up the mantle in the second half of the 20th century, employing computers to help him realize physical metaphors based especially in statistical mechanics [@xenakis_formalized_1992]. Curtis Roads carried this approach into the 21st century, pioneering granular synthesis as a means of composing with clouds of sound, which, in his own compositions, evolve and interact in deeply physical ways [@roads_composing_2015].

So far my compositional approach to physical metaphor has been most fully realized in *De Rerum Natura*, which I first completed in 2019 and revised in 2020. 

The piece begins with a metallic sound crashing onto the soundfield, throwing up a flurry of shrapnel that slowly settles onto a calm glassy surface. A new sound then swirls into the scene and kicks up the dust again. Emerging from the debris, a fluttering sound seems to strike a match that heats up another sound that builds up to an explosion. The fallout of the explosion is swept away unexpectedly by another clattering sound which sets up a domino effect leading to a door opening into a noisy soundscape. This is just one interpretation, but it illustrates how every sound in the piece has the illusion of being part of a physical chain of events.

In *Coacervate* (2020) for Violin and Electronics, different physical interactions are explored. The piece takes place inside an imaginary test tube or beaker filled with various liquid components. The sounds in this piece tend to float through the musical texture before suddenly and sometimes violently coalescing into droplets. Other times the sound field seems to get stirred up as a new component gets added into the mix. This all reflects the chemical process which gave the piece it's name.

While this kind of imagined field of interactions among sounds can be fruitful, and I will continue to compose in this way, I also have a desire to express more complex physical gestures in my music that require some computation. This is why I have created CHON.
